/**
 * Canonical workflow statuses for Quick Commerce orders (v2).
 * Legacy `status` on Order is kept in sync for admin / older UIs.
 */
export const WORKFLOW_STATUS = {
  ORDER_PLACED: "ORDER_PLACED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  INVENTORY_RESERVED: "INVENTORY_RESERVED",
  PROCUREMENT_REQUIRED: "PROCUREMENT_REQUIRED",
  PROCUREMENT_COMPLETED: "PROCUREMENT_COMPLETED",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  PICKUP_ASSIGNED: "PICKUP_ASSIGNED",
  SELLER_READY: "SELLER_READY",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT_TO_HUB: "IN_TRANSIT_TO_HUB",
  RECEIVED_AT_HUB: "RECEIVED_AT_HUB",
  QA_PENDING: "QA_PENDING",
  QA_PASSED: "QA_PASSED",
  PACKING: "PACKING",
  READY_FOR_DELIVERY: "READY_FOR_DELIVERY",
  DELIVERY_OTP_VERIFIED: "DELIVERY_OTP_VERIFIED",
  RETURN_REQUESTED: "RETURN_REQUESTED",
  RETURN_APPROVED: "RETURN_APPROVED",
  RETURN_PICKUP_ASSIGNED: "RETURN_PICKUP_ASSIGNED",
  RETURN_PICKED: "RETURN_PICKED",
  RETURN_RECEIVED_AT_HUB: "RETURN_RECEIVED_AT_HUB",
  RETURN_QA: "RETURN_QA",
  REFUND_INITIATED: "REFUND_INITIATED",
  REFUND_COMPLETED: "REFUND_COMPLETED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PROCUREMENT_FAILED: "PROCUREMENT_FAILED",
  SELLER_REJECTED: "SELLER_REJECTED",
  SELLER_TIMEOUT: "SELLER_TIMEOUT",
  QA_FAILED: "QA_FAILED",
  PICKUP_FAILED: "PICKUP_FAILED",
  DELIVERY_FAILED: "DELIVERY_FAILED",
  RETURN_REJECTED: "RETURN_REJECTED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  CREATED: "CREATED",
  SELLER_PENDING: "SELLER_PENDING",
  SELLER_ACCEPTED: "SELLER_ACCEPTED",
  DELIVERY_SEARCH: "DELIVERY_SEARCH",
  DELIVERY_ASSIGNED: "DELIVERY_ASSIGNED",
  PICKUP_READY: "PICKUP_READY",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

/** Milliseconds — override via env in services */
export const DEFAULT_SELLER_TIMEOUT_MS = () =>
  parseInt(process.env.SELLER_TIMEOUT_MS || "60000", 10);
export const DEFAULT_DELIVERY_TIMEOUT_MS = () =>
  parseInt(
    process.env.DELIVERY_TIMEOUT_MS ||
      process.env.DEFAULT_DELIVERY_TIMEOUT_MS ||
      "60000",
    10,
  );

/**
 * Map workflow -> legacy `status` string (existing enum on Order schema).
 */
export function legacyStatusFromWorkflow(workflowStatus) {
  switch (workflowStatus) {
    case WORKFLOW_STATUS.ORDER_PLACED:
      return "pending";
    case WORKFLOW_STATUS.PAYMENT_CONFIRMED:
    case WORKFLOW_STATUS.INVENTORY_RESERVED:
    case WORKFLOW_STATUS.PROCUREMENT_REQUIRED:
    case WORKFLOW_STATUS.PROCUREMENT_COMPLETED:
    case WORKFLOW_STATUS.READY_FOR_PICKUP:
    case WORKFLOW_STATUS.PICKUP_ASSIGNED:
    case WORKFLOW_STATUS.SELLER_READY:
    case WORKFLOW_STATUS.PICKED_UP:
    case WORKFLOW_STATUS.IN_TRANSIT_TO_HUB:
    case WORKFLOW_STATUS.RECEIVED_AT_HUB:
    case WORKFLOW_STATUS.QA_PENDING:
    case WORKFLOW_STATUS.QA_PASSED:
    case WORKFLOW_STATUS.PACKING:
    case WORKFLOW_STATUS.READY_FOR_DELIVERY:
      return "confirmed";
    case WORKFLOW_STATUS.DELIVERY_OTP_VERIFIED:
      return "out_for_delivery";
    case WORKFLOW_STATUS.ORDER_CANCELLED:
    case WORKFLOW_STATUS.PAYMENT_FAILED:
    case WORKFLOW_STATUS.PROCUREMENT_FAILED:
    case WORKFLOW_STATUS.SELLER_REJECTED:
    case WORKFLOW_STATUS.SELLER_TIMEOUT:
    case WORKFLOW_STATUS.QA_FAILED:
    case WORKFLOW_STATUS.PICKUP_FAILED:
    case WORKFLOW_STATUS.DELIVERY_FAILED:
      return "cancelled";
    case WORKFLOW_STATUS.CREATED:
      return "pending";
    case WORKFLOW_STATUS.SELLER_PENDING:
      return "pending";
    case WORKFLOW_STATUS.SELLER_ACCEPTED:
      return "confirmed";
    case WORKFLOW_STATUS.DELIVERY_SEARCH:
      return "confirmed";
    case WORKFLOW_STATUS.DELIVERY_ASSIGNED:
      return "confirmed";
    case WORKFLOW_STATUS.PICKUP_READY:
      return "confirmed";
    case WORKFLOW_STATUS.OUT_FOR_DELIVERY:
      return "out_for_delivery";
    case WORKFLOW_STATUS.DELIVERED:
      return "delivered";
    case WORKFLOW_STATUS.CANCELLED:
      return "cancelled";
    default:
      return "pending";
  }
}

/**
 * Infer workflow from legacy `status` when workflowVersion < 2 or missing workflowStatus.
 */
export function workflowFromLegacyStatus(legacy) {
  const s = (legacy || "").toLowerCase();
  if (s === "pending") return WORKFLOW_STATUS.SELLER_PENDING;
  if (s === "confirmed") return WORKFLOW_STATUS.DELIVERY_SEARCH;
  if (s === "packed") return WORKFLOW_STATUS.DELIVERY_ASSIGNED;
  if (s === "out_for_delivery") return WORKFLOW_STATUS.OUT_FOR_DELIVERY;
  if (s === "delivered") return WORKFLOW_STATUS.DELIVERED;
  if (s === "cancelled") return WORKFLOW_STATUS.CANCELLED;
  return WORKFLOW_STATUS.SELLER_PENDING;
}
